version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  bank-core:
    build:
      context: bank-core-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - bank

  atm-client:
    build:
      context: atm-client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - bank
      - host

networks:
  postgres:
  bank:
  host:
    external: true

volumes:
  postgres:
